### ISSUE TITLE
After updating to 1.5.0 from 1.4.2 got panic: send on closed channel 

### ISSUE THREAD

**Issue by astudnev** [eientei/wsgraphql#4]
**Describe the bug**

Updating from 1.4.2 -> 1.5.0 

**Log**
```
panic: send on closed channel
goroutine 40920614 [running]:
github.com/eientei/wsgraphql/v1.(*websocketRequest).handleError(0xc007c7e880, {0x1890f80, 0xc03e21a780}, {0x1888d20?, 0x18836f8}, 0x0)
	github.com/eientei/wsgraphql@v1.4.2/v1/server_websocket.go:162 +0x1a5
```

**Comment by iamtakingiteasy** [comment]
@astudnev Error indicates you're still using 1.4.2.

**Comment by iamtakingiteasy** [comment]
1.5.0 had this race condition fixed, make sure your outermost go.mod has correct version. Also note that latest version is 1.5.1, though it's changes should not be relevant to the issue.

Race condition fix can be backported to 1.4.x, but I would suggest updating to 1.5.x, there is some other improvements as well.

**Comment by astudnev** [comment]
It looked for us that it is just opposite - we run successfully on 1.4.2 and when updating to 1.5.0 this panic happens pretty fast

**Comment by iamtakingiteasy** [comment]
Error provided contains

> 	github.com/eientei/wsgraphql@v1.4.2/v1/server_websocket.go:162 +0x1a5

Indicating 1.4.2 module version is used and line numbering is consistent with 1.4.2 version.

**Comment by iamtakingiteasy** [comment]
If you are able to reproduce similar issue on 1.5.0, please provide full error log. If you have a minimal reproducing example, it would also be helpful. As far as I can see, you're actually using 1.4.2 and 1.5.0 specifically added request context bound to the background timeout. It should not happen when 1.5.0 is actually used.

**Comment by astudnev** [comment]
Log i have now is:

```
panic: send on closed channel

goroutine 40920614 [running]:
[github.com/eientei/wsgraphql/v1.(*websocketRequest](http://github.com/eientei/wsgraphql/v1.(*websocketRequest)).handleError(0xc007c7e880, {0x1890f80, 0xc03e21a780}, {0x1888d20?, 0x18836f8}, 0x0)
	[github.com/eientei/wsgraphql@v1.4.2/v1/server_websocket.go:162](http://github.com/eientei/wsgraphql@v1.4.2/v1/server_websocket.go:162) +0x1a5
[github.com/eientei/wsgraphql/v1.(*websocketRequest](http://github.com/eientei/wsgraphql/v1.(*websocketRequest)).readWebsocket.func2()
	[github.com/eientei/wsgraphql@v1.4.2/v1/server_websocket.go:351](http://github.com/eientei/wsgraphql@v1.4.2/v1/server_websocket.go:351) +0x9a
created by [github.com/eientei/wsgraphql/v1.(*websocketRequest](http://github.com/eientei/wsgraphql/v1.(*websocketRequest)).readWebsocket
	[github.com/eientei/wsgraphql@v1.4.2/v1/server_websocket.go:348](http://github.com/eientei/wsgraphql@v1.4.2/v1/server_websocket.go:348) +0xfb
```

**Comment by astudnev** [comment]
Sory... that was on 1.4.2
